

run: main.cpp
	g++ "main.cpp" -o main.exe -O0 -std=c++17 -lraylib -lopengl32 -lgdi32 -lwinmm -lpthread -static --fast-math
	.\main.exe

final: main.cpp
	g++ "main.cpp" -o a.exe -O3 -Wall -Wno-missing-braces -std=c++17 -lraylib -lopengl32 -lgdi32 -lwinmm -static --fast-math


